repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest tag from https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/psf/black
    rev: 23.3.0  # Use the latest tag from https://github.com/psf/black/releases
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Use the latest tag from https://github.com/PyCQA/flake8/releases
    hooks:
      - id: flake8
        args: [ --max-line-length=130 ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0  # Use the latest tag from https://github.com/pre-commit/mirrors-mypy/releases
    hooks:
      - id: mypy

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [ cython ]
      - id: isort
        name: isort (pyi)
        types: [ pyi ]
